@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
Class "<<interface>>\nUi" as Ui
Class "      {abstract}      \nUiPart" as UiPart

Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class StatusBarFooter
Class CommandBox
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager ..up|> Ui
UiManager -right> Logic
UiManager --down> "1" MainWindow
Model -left[hidden]> Logic

PersonListPanel -|> UiPart
StatusBarFooter -|> UiPart
ResultDisplay -|> UiPart
CommandBox -|> UiPart
HelpWindow -|> UiPart
MainWindow ---------|> UiPart

PersonCard --|> UiPart

MainWindow --up> Logic
MainWindow *-down> "1  " StatusBarFooter
MainWindow *-down> "1  " ResultDisplay
MainWindow *-down> "1  " CommandBox
MainWindow *-down> "1     " HelpWindow
MainWindow *-down> "1  " PersonListPanel

PersonListPanel --down> " *" PersonCard
PersonListPanel ....> Model
PersonCard ..up> Model

StatusBarFooter --[hidden]> PersonListPanel
ResultDisplay --[hidden]> StatusBarFooter
CommandBox --[hidden]> ResultDisplay
HelpWindow --[hidden]> CommandBox

@enduml
