@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-left-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueGroupList

UniquePersonList -right-> Person
UniqueGroupList -right-> "*" Group

Group *--> GroupName
Group *-down-> "1" UniqueAssignmentList
UniqueAssignmentList -right-> "*" Assignment
Assignment *--> AssignmentName

Person --up> "*" Tag
Person -right-> "*" GroupName
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> MatricNumber
Person *-down-> "*" SessionList

SessionList -right-> "*" Session
Session *--> LocalDate
Session *--> Attendance
Session *--> Participation

Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> MatricNumber
GroupName -[hidden]down-> Assignment
@enduml
